# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 08:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)])),
                ('Added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupID', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IRcommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commend', models.CharField(max_length=100)),
                ('RawCode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Address', models.IntegerField()),
                ('Type', models.CharField(max_length=2)),
                ('Appliances', models.CharField(max_length=100)),
                ('Added', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='api.House')),
            ],
        ),
        migrations.CreateModel(
            name='NodeState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=100)),
                ('Added', models.DateTimeField(auto_now_add=True)),
                ('NodeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='api.Nodes')),
            ],
        ),
        migrations.AddField(
            model_name='ircommend',
            name='NodeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IRcom', to='api.Nodes'),
        ),
        migrations.AddField(
            model_name='currentstate',
            name='NodeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_states', to='api.Nodes'),
        ),
    ]
