# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 06:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='Added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='Updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
