# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160129_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggerTime', models.DateTimeField()),
                ('Commend', models.CharField(max_length=100)),
                ('completed', models.BooleanField()),
                ('gueued', models.BooleanField()),
                ('NodeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tasks', to='api.Nodes')),
            ],
        ),
    ]
