# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_taskschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskschedule',
            old_name='gueued',
            new_name='queued',
        ),
        migrations.AlterField(
            model_name='nodes',
            name='Address',
            field=models.CharField(max_length=100),
        ),
    ]
